name: Verify

on:
    workflow_dispatch:
    pull_request:

permissions:
    id-token: write
    contents: read

jobs:
    verify:
        name: Verify and Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            # - name: Setup Node
            #   uses: actions/setup-node@v3
            #   with:
            #       node-version-file: '.nvmrc'

            # - name: Install
            #   run: |
            #       npm ci

            # - name: Verify
            #   run: |
            #       npm run verify

            # - name: Build
            #   run: |
            #       npm run build

            - name: Create Check Run
              uses: actions/github-script@v5
              with:
                  script: |
                      await github.rest.checks.create({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        name: 'Verify and Build',
                        head_sha: context.sha,
                      })
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}